//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIBOST1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_UserGroup
    {
        public string UserID { get; set; }
        public string UserGroupID { get; set; }
    }
}
