//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIBOST1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vContactUser
    {
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public string Manager { get; set; }
        public string DirectReports { get; set; }
        public string Extension { get; set; }
        public string EmailAddress { get; set; }
        public string Mobile { get; set; }
        public string EmployeeID { get; set; }
        public string Office { get; set; }
        public string ThumbnailPhoto { get; set; }
        public string Photo { get; set; }
        public string TelephoneNumber { get; set; }
        public string Fax { get; set; }
        public string NickName { get; set; }
        public int UserAccountControl { get; set; }
        public string UserAccountControlBinary { get; set; }
    }
}
